// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/qh_data_grpc_service.proto

package qh_data_service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type QILRequest struct {
	QilID                int64    `protobuf:"varint,1,opt,name=qilID,proto3" json:"qilID,omitempty"`
	QilVersion           int64    `protobuf:"varint,2,opt,name=qilVersion,proto3" json:"qilVersion,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QILRequest) Reset()         { *m = QILRequest{} }
func (m *QILRequest) String() string { return proto.CompactTextString(m) }
func (*QILRequest) ProtoMessage()    {}
func (*QILRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d6ff73d771d4763, []int{0}
}

func (m *QILRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QILRequest.Unmarshal(m, b)
}
func (m *QILRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QILRequest.Marshal(b, m, deterministic)
}
func (m *QILRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QILRequest.Merge(m, src)
}
func (m *QILRequest) XXX_Size() int {
	return xxx_messageInfo_QILRequest.Size(m)
}
func (m *QILRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QILRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QILRequest proto.InternalMessageInfo

func (m *QILRequest) GetQilID() int64 {
	if m != nil {
		return m.QilID
	}
	return 0
}

func (m *QILRequest) GetQilVersion() int64 {
	if m != nil {
		return m.QilVersion
	}
	return 0
}

type QILResponse struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QILResponse) Reset()         { *m = QILResponse{} }
func (m *QILResponse) String() string { return proto.CompactTextString(m) }
func (*QILResponse) ProtoMessage()    {}
func (*QILResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d6ff73d771d4763, []int{1}
}

func (m *QILResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QILResponse.Unmarshal(m, b)
}
func (m *QILResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QILResponse.Marshal(b, m, deterministic)
}
func (m *QILResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QILResponse.Merge(m, src)
}
func (m *QILResponse) XXX_Size() int {
	return xxx_messageInfo_QILResponse.Size(m)
}
func (m *QILResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QILResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QILResponse proto.InternalMessageInfo

func (m *QILResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*QILRequest)(nil), "qh_data_service.QILRequest")
	proto.RegisterType((*QILResponse)(nil), "qh_data_service.QILResponse")
}

func init() {
	proto.RegisterFile("proto/qh_data_grpc_service.proto", fileDescriptor_3d6ff73d771d4763)
}

var fileDescriptor_3d6ff73d771d4763 = []byte{
	// 180 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x28, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0xcc, 0x88, 0x4f, 0x49, 0x2c, 0x49, 0x8c, 0x4f, 0x2f, 0x2a, 0x48, 0x8e, 0x2f,
	0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x03, 0x4b, 0x09, 0xf1, 0xc3, 0xe4, 0xa0, 0xc2, 0x4a,
	0x4e, 0x5c, 0x5c, 0x81, 0x9e, 0x3e, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0x22, 0x5c,
	0xac, 0x85, 0x99, 0x39, 0x9e, 0x2e, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xcc, 0x41, 0x10, 0x8e, 0x90,
	0x1c, 0x17, 0x57, 0x61, 0x66, 0x4e, 0x58, 0x6a, 0x51, 0x71, 0x66, 0x7e, 0x9e, 0x04, 0x13, 0x58,
	0x0a, 0x49, 0x44, 0x49, 0x91, 0x8b, 0x1b, 0x6c, 0x46, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0xaa, 0x90,
	0x10, 0x17, 0x0b, 0xc8, 0x0a, 0xb0, 0x19, 0x9c, 0x41, 0x60, 0xb6, 0x51, 0x00, 0x17, 0x5b, 0xa0,
	0x87, 0x4b, 0x62, 0x49, 0xa2, 0x90, 0x1b, 0x17, 0xbb, 0x73, 0x62, 0x4e, 0x4e, 0x60, 0x66, 0x8e,
	0x90, 0xb4, 0x1e, 0x9a, 0x6b, 0xf4, 0x10, 0x4e, 0x91, 0x92, 0xc1, 0x2e, 0x09, 0xb1, 0x43, 0x89,
	0x21, 0x89, 0x0d, 0xec, 0x21, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x31, 0xda, 0xb2, 0xec,
	0xf4, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// QHDataClient is the client API for QHData service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QHDataClient interface {
	CallQil(ctx context.Context, in *QILRequest, opts ...grpc.CallOption) (*QILResponse, error)
}

type qHDataClient struct {
	cc grpc.ClientConnInterface
}

func NewQHDataClient(cc grpc.ClientConnInterface) QHDataClient {
	return &qHDataClient{cc}
}

func (c *qHDataClient) CallQil(ctx context.Context, in *QILRequest, opts ...grpc.CallOption) (*QILResponse, error) {
	out := new(QILResponse)
	err := c.cc.Invoke(ctx, "/qh_data_service.QHData/CallQil", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QHDataServer is the server API for QHData service.
type QHDataServer interface {
	CallQil(context.Context, *QILRequest) (*QILResponse, error)
}

// UnimplementedQHDataServer can be embedded to have forward compatible implementations.
type UnimplementedQHDataServer struct {
}

func (*UnimplementedQHDataServer) CallQil(ctx context.Context, req *QILRequest) (*QILResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CallQil not implemented")
}

func RegisterQHDataServer(s *grpc.Server, srv QHDataServer) {
	s.RegisterService(&_QHData_serviceDesc, srv)
}

func _QHData_CallQil_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QILRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QHDataServer).CallQil(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qh_data_service.QHData/CallQil",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QHDataServer).CallQil(ctx, req.(*QILRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _QHData_serviceDesc = grpc.ServiceDesc{
	ServiceName: "qh_data_service.QHData",
	HandlerType: (*QHDataServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CallQil",
			Handler:    _QHData_CallQil_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/qh_data_grpc_service.proto",
}
